accounts:
  - name: alice
    coins: ['1000token', '100000000stake']
  - name: bob
    coins: ['500token']
  - name: val2
    coins: ['400token']
  - name: val3
    coins: ['500token']
validator:
  name: alice
  staked: '100000000stake'
genesis:
  app_state:
    oracle:
      params:
        claim_params:
          AtomClaim: # This is our oracle 'type'
            vote_period: 3 # Voting round duration in blocks
            claim_type: 'AtomClaim' # Oracle type again
            prevote: true # Require commit-reveal type voting to avoid free-rider problem
            vote_threshold: '0.5' # Validator power threshold required to reach consensus
