version: '3'

services:
  gaiadnode0:
    container_name: oracle0
    image: 'relevant/oracle'
    ports:
      - '26656-26657:26656-26657'
    environment:
      - ID=0
      - LOG=${LOG:-oracled.log}
    volumes:
      - ./build:/oracled:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  gaiadnode1:
    container_name: oracle1
    image: 'relevant/oracle'
    ports:
      - '26659-26660:26656-26657'
    environment:
      - ID=1
      - LOG=${LOG:-oracled.log}
    volumes:
      - ./build:/oracled:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  gaiadnode2:
    container_name: oracle2
    image: 'relevant/oracle'
    environment:
      - ID=2
      - LOG=${LOG:-oracled.log}
    ports:
      - '26661-26662:26656-26657'
    volumes:
      - ./build:/oracled:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  gaiadnode3:
    container_name: oracle3
    image: 'relevant/oracle'
    environment:
      - ID=3
      - LOG=${LOG:-oracled.log}
    ports:
      - '26663-26664:26656-26657'
    volumes:
      - ./build:/oracled:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/16
